name: github 001

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: shuifan-open/github-repository-sync-action@v3
        with:
          secret_config: ${{ secrets.SECRET_CONFIG }}
          variable_config: ${{ vars.VARIABLE_CONFIG }}
